// Code generated by mockery v1.0.0. DO NOT EDIT.

package persistencemocks

import (
	context "context"

	fftypes "github.com/hyperledger/firefly-common/pkg/fftypes"
	fftm "github.com/hyperledger/firefly-transaction-manager/pkg/fftm"

	mock "github.com/stretchr/testify/mock"
)

// Persistence is an autogenerated mock type for the Persistence type
type Persistence struct {
	mock.Mock
}

// DeleteCheckpoint provides a mock function with given fields: ctx, streamID
func (_m *Persistence) DeleteCheckpoint(ctx context.Context, streamID *fftypes.UUID) error {
	ret := _m.Called(ctx, streamID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.UUID) error); ok {
		r0 = rf(ctx, streamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteListener provides a mock function with given fields: ctx, listenerID
func (_m *Persistence) DeleteListener(ctx context.Context, listenerID *fftypes.UUID) error {
	ret := _m.Called(ctx, listenerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.UUID) error); ok {
		r0 = rf(ctx, listenerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteStream provides a mock function with given fields: ctx, streamID
func (_m *Persistence) DeleteStream(ctx context.Context, streamID *fftypes.UUID) error {
	ret := _m.Called(ctx, streamID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.UUID) error); ok {
		r0 = rf(ctx, streamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetListener provides a mock function with given fields: ctx, listenerID
func (_m *Persistence) GetListener(ctx context.Context, listenerID *fftypes.UUID) (*fftm.Listener, error) {
	ret := _m.Called(ctx, listenerID)

	var r0 *fftm.Listener
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.UUID) *fftm.Listener); ok {
		r0 = rf(ctx, listenerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fftm.Listener)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *fftypes.UUID) error); ok {
		r1 = rf(ctx, listenerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStream provides a mock function with given fields: ctx, streamID
func (_m *Persistence) GetStream(ctx context.Context, streamID *fftypes.UUID) (*fftm.EventStream, error) {
	ret := _m.Called(ctx, streamID)

	var r0 *fftm.EventStream
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.UUID) *fftm.EventStream); ok {
		r0 = rf(ctx, streamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fftm.EventStream)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *fftypes.UUID) error); ok {
		r1 = rf(ctx, streamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListListeners provides a mock function with given fields: ctx, after, limit
func (_m *Persistence) ListListeners(ctx context.Context, after *fftypes.UUID, limit int) ([]*fftm.Listener, error) {
	ret := _m.Called(ctx, after, limit)

	var r0 []*fftm.Listener
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.UUID, int) []*fftm.Listener); ok {
		r0 = rf(ctx, after, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*fftm.Listener)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *fftypes.UUID, int) error); ok {
		r1 = rf(ctx, after, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListStreamListeners provides a mock function with given fields: ctx, after, limit, streamID
func (_m *Persistence) ListStreamListeners(ctx context.Context, after *fftypes.UUID, limit int, streamID *fftypes.UUID) ([]*fftm.Listener, error) {
	ret := _m.Called(ctx, after, limit, streamID)

	var r0 []*fftm.Listener
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.UUID, int, *fftypes.UUID) []*fftm.Listener); ok {
		r0 = rf(ctx, after, limit, streamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*fftm.Listener)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *fftypes.UUID, int, *fftypes.UUID) error); ok {
		r1 = rf(ctx, after, limit, streamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListStreams provides a mock function with given fields: ctx, after, limit
func (_m *Persistence) ListStreams(ctx context.Context, after *fftypes.UUID, limit int) ([]*fftm.EventStream, error) {
	ret := _m.Called(ctx, after, limit)

	var r0 []*fftm.EventStream
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.UUID, int) []*fftm.EventStream); ok {
		r0 = rf(ctx, after, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*fftm.EventStream)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *fftypes.UUID, int) error); ok {
		r1 = rf(ctx, after, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCheckpoint provides a mock function with given fields: ctx, streamID
func (_m *Persistence) GetCheckpoint(ctx context.Context, streamID *fftypes.UUID) (*fftm.EventStreamCheckpoint, error) {
	ret := _m.Called(ctx, streamID)

	var r0 *fftm.EventStreamCheckpoint
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.UUID) *fftm.EventStreamCheckpoint); ok {
		r0 = rf(ctx, streamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fftm.EventStreamCheckpoint)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *fftypes.UUID) error); ok {
		r1 = rf(ctx, streamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteCheckpoint provides a mock function with given fields: ctx, checkpoint
func (_m *Persistence) WriteCheckpoint(ctx context.Context, checkpoint *fftm.EventStreamCheckpoint) error {
	ret := _m.Called(ctx, checkpoint)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftm.EventStreamCheckpoint) error); ok {
		r0 = rf(ctx, checkpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteListener provides a mock function with given fields: ctx, spec
func (_m *Persistence) WriteListener(ctx context.Context, spec *fftm.Listener) error {
	ret := _m.Called(ctx, spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftm.Listener) error); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteStream provides a mock function with given fields: ctx, spec
func (_m *Persistence) WriteStream(ctx context.Context, spec *fftm.EventStream) error {
	ret := _m.Called(ctx, spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftm.EventStream) error); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
