// Code generated by mockery v1.0.0. DO NOT EDIT.

package managermocks

import mock "github.com/stretchr/testify/mock"

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *Manager) Start() {
	_m.Called()
}

// WaitStop provides a mock function with given fields:
func (_m *Manager) WaitStop() {
	_m.Called()
}
