// Code generated by mockery v1.0.0. DO NOT EDIT.

package managermocks

import mock "github.com/stretchr/testify/mock"

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *Manager) Start() {
	_m.Called()
}

// WaitStop provides a mock function with given fields:
func (_m *Manager) WaitStop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
