// Code generated by mockery v1.0.0. DO NOT EDIT.

package confirmationsmocks

import (
	confirmations "github.com/hyperledger/firefly-transaction-manager/internal/confirmations"
	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// Notify provides a mock function with given fields: n
func (_m *Manager) Notify(n *confirmations.Notification) error {
	ret := _m.Called(n)

	var r0 error
	if rf, ok := ret.Get(0).(func(*confirmations.Notification) error); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *Manager) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *Manager) Stop() {
	_m.Called()
}
