// Code generated by mockery v2.40.2. DO NOT EDIT.

package fftmmocks

import (
	context "context"

	apitypes "github.com/hyperledger/firefly-transaction-manager/pkg/apitypes"

	mock "github.com/stretchr/testify/mock"
)

// ModuleFunctions is an autogenerated mock type for the ModuleFunctions type
type ModuleFunctions struct {
	mock.Mock
}

// ProcessBatchedEvents provides a mock function with given fields: ctx, batchNumber, attempt, events
func (_m *ModuleFunctions) ProcessBatchedEvents(ctx context.Context, batchNumber int64, attempt int, events []*apitypes.EventWithContext) error {
	ret := _m.Called(ctx, batchNumber, attempt, events)

	if len(ret) == 0 {
		panic("no return value specified for ProcessBatchedEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, []*apitypes.EventWithContext) error); ok {
		r0 = rf(ctx, batchNumber, attempt, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModuleFunctions creates a new instance of ModuleFunctions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModuleFunctions(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModuleFunctions {
	mock := &ModuleFunctions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
