{
 "title": "Event process metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Receipt process duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(ff_events_receipt_process_duration_seconds_bucket{job=~\"$Job\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Confirmation duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "increase(ff_events_confirmation_process_duration_seconds_bucket{job=~\"$Job\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg receipt processed (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(rate(ff_events_receipt_processed_total{job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg confirmations (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "avg (rate(ff_events_confirmation_processed_total{job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "[Internal] receipt checker (queries receipt for each transaction on blockchain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Receipt check duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(ff_events_receipt_check_duration_seconds_bucket{job=~\"$Job\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg tx receipt check request result count ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "avg by(status) (rate(ff_events_receipt_check_total{job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "[Internal] async instructions(notifications) process queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Joining queue duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "increase(ff_events_notification_queueing_duration_seconds_bucket{job=~\"$Job\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queueing duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "increase(ff_events_notification_process_seconds_bucket{job=~\"$Job\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Joining queue count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "avg by(type) (rate(ff_events_notification_queued_total{job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Processed count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "avg by(type) (rate(ff_events_notification_processed_total{job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "[Internal] Block process queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Joining queue duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "increase(ff_events_block_hash_queueing_duration_seconds_bucket{job=~\"$Job\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queueing duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "increase(ff_events_block_hash_process_duration_seconds_bucket{job=~\"$Job\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Joining queue count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "avg(rate(ff_events_block_hash_queued_total{job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Process count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "avg (rate(ff_events_block_hash_processed_total{job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}