// Code generated by mockery v2.40.2. DO NOT EDIT.

package eventsmocks

import (
	context "context"

	apitypes "github.com/hyperledger/firefly-transaction-manager/pkg/apitypes"

	mock "github.com/stretchr/testify/mock"
)

// InternalEventsDispatcher is an autogenerated mock type for the InternalEventsDispatcher type
type InternalEventsDispatcher struct {
	mock.Mock
}

// ProcessBatchedEvents provides a mock function with given fields: ctx, batchNumber, attempt, _a3
func (_m *InternalEventsDispatcher) ProcessBatchedEvents(ctx context.Context, batchNumber int64, attempt int, _a3 []*apitypes.EventWithContext) error {
	ret := _m.Called(ctx, batchNumber, attempt, _a3)

	if len(ret) == 0 {
		panic("no return value specified for ProcessBatchedEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, []*apitypes.EventWithContext) error); ok {
		r0 = rf(ctx, batchNumber, attempt, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInternalEventsDispatcher creates a new instance of InternalEventsDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternalEventsDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternalEventsDispatcher {
	mock := &InternalEventsDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
